apiVersion: v1
data:
  server.conf: |
    server {
      spire_socket_path = "unix:///tmp/spire-server/private/api.sock" # socket to communicate with SPIRE server
      http {
        enabled = true # if true, opens HTTP server
        port = "10000" # if HTTP enabled, opens HTTP listen port at specified container port
      }
    }

    plugins {
      DataStore "sql" {
        plugin_data {
          drivername = "sqlite3"
          filename = "/run/spire/data/tornjak.sqlite3"
        }
      }
      SPIRECRDManager {
        plugin_data {
          classname = "spire-mgmt-spire"
        }
      }
    }
kind: ConfigMap
metadata:
  name: spire-tornjak-config
  namespace: spire-server
