apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: spire-mgmt-spire-default
spec:
  className: spire-mgmt-spire
  fallback: false
  hint: default
  federatesWith: ["$APP_DOMAIN"]
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - spire-mgmt
      - spire-server
      - spire-system
  spiffeIDTemplate: spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{
    .PodSpec.ServiceAccountName }}
