global:
  openshift: false # If running on openshift, set to true
  spire:
    recommendations:
      enabled: true
    namespaces:
      create: true
    ingressControllerType: "" # If not openshift, and want to expose services, set to a supported option [ingress-nginx]
    # Update these
    clusterName: client-cluster
    trustDomain: client.example #$APP_DOMAIN
    caSubject:
      country: SPIFFE
      organization: TornjakFederationDemo
      commonName: client.example #$APP_DOMAIN

spire-server:
  #ingress:
  #enabled: true
  tornjak:
    #ingress:
    #enabled: true
    enabled: true
    image:
      tag: 71e87dc17afd66e42ab70e3004d833175d63a167

tornjak-frontend:
  enabled: true
  image:
    tag: v1.9.0
  #ingress:
  #enabled: true
  apiServerURL: https://host.docker.internal:10001 #$APP_DOMAIN
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 512Mi
